=== Mirf2404/Lenguaje-de-marcas/XML/XSD_Y_XML_EJ1/Schema.xsd
<xs:schema xmlns="EJ1" targetNamespace="EJ1" elementFormDefault="qualified"   xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="mensaje">
        
    
    
    
        <xs:complexType>

            <xs:sequence>
                <xs:element name="remitente"  minOccurs="0" maxOccurs="unbounded">
                 <xs:complexType>

                    <xs:sequence>
                        <xs:element  name="nombre" type="xs:string"/>
                        <xs:element  name="email" type="xs:string"/>
                    </xs:sequence>
    
                 </xs:complexType>

                </xs:element> 


            <xs:element name="destinatario"  minOccurs="0" maxOccurs="unbounded">

                    <xs:complexType>

                        <xs:sequence>
                            <xs:element  name="nombre" type="xs:string"/>
                            <xs:element  name="email">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="(\. text+)*@text+(\.text+)*"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            
                            </xs:element>
                        </xs:sequence>

                    </xs:complexType>

                </xs:element> 


                <xs:element name="asunto"/>
                <xs:element name="texto">
                 <xs:complexType>
                    <xs:sequence>
                        <xs:element name="parrafo" type="xs:string"></xs:element>
                    </xs:sequence>
                 </xs:complexType>

                </xs:element>
            </xs:sequence>
    
        </xs:complexType>

       
            
        
            

        

    

   


    
       
  
    </xs:element>
</xs:schema>

=== Mirf2404/Lenguaje-de-marcas/XML/XSD_Y_XML_EJ1/XSD_XML_EJ1.xml
<?xml version="1.0" encoding="UTF-8"?>
<mensaje xmlns="EJ1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="EJ1 Schema.xsd"  >

<remitente>
    <nombre></nombre>
    <email></email>
</remitente>
<destinatario>
    <nombre></nombre>
    <email>
        a.aa@aaaaa

    </email>
</destinatario>
<asunto></asunto>
<texto>
    <parrafo></parrafo>
</texto>
</mensaje>
