=== Mirf2404/Lenguaje-de-marcas/XML/XSD_Y_XML_EJ3/SchemaEJ3.xsd
<xs:schema xmlns="EJ3" targetNamespace="EJ3" elementFormDefault="qualified"
    xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="cancion" type="T_Cancion">
        
        
    </xs:element>
   
      
    <xs:complexType name="T_Cancion">
        
            
      
        <xs:sequence>
            <xs:element name="titulo" type="xs:string" />
            <xs:element name="compositores" type="tipoComp">

            </xs:element>
            <xs:element name="productores" type="tipoComp2" />
            <xs:element name="sello" type="xs:string" />
            <xs:element name="artista" type="xs:string" />


        </xs:sequence>

        <xs:attribute name="duracion" type="xs:string" />
        <xs:attribute name="anio" type="xs:gYear" />
    </xs:complexType>
 

    <xs:complexType name="tipoComp">

        <xs:sequence>
            <xs:element name="compositor" type="tipocompos" />
        </xs:sequence>

    </xs:complexType>

    <xs:complexType name="tipoComp2">

        <xs:sequence>
            <xs:element name="productor" type="tipocompos" />
        </xs:sequence>

    </xs:complexType>
    <xs:complexType name="tipocompos">

        <xs:sequence>
            <xs:element name="nombre" type="xs:string" />
            <xs:element name="apellidos" type="xs:string" />
        </xs:sequence>

    </xs:complexType>

</xs:schema>

=== Mirf2404/Lenguaje-de-marcas/XML/XSD_Y_XML_EJ3/XSD_XML_EJ3.xml
<?xml version="1.0" encoding="UTF-8"?>
<cancion xmlns="EJ3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="EJ3 SchemaEJ3.xsd"  >

<titulo>Give it 2 me </titulo>
<compositores>
<compositor>

    <nombres>Pharrell</nombres>
    <apellidos>Williams</apellidos>
</compositor>
</compositores>

<productores>
    <productor>
        <nombres>Pharrell</nombres>
        <apellidos>Williams</apellidos>
    </productor>
</productores>

<sello>Warner Bros. Records</sello>
<artista>Madonna</artista>












</cancion>
