=== Mirf2404/Lenguaje-de-marcas/XML/XML_TRABAJO/TRABAJOSCHEMA.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"  elementFormDefault="qualified" targetNamespace="ejer" xmlns="ejer" >
    <xs:element name="curriculum" type="q">
       
    </xs:element>
    <xs:complexType name="q">
        <xs:sequence>
            <xs:element name="datos_perso" type="datos_personales1"/>
            <xs:element name="datos_contacto" type="datos_contacto1"/>
            <xs:element name="formacion_academica" type="formacion_academica1"/>
            <xs:element name="idiomas" type="idiomas1"/>
            <xs:element name="experiencia_laboral" type="experiencia_laboral1"/>
            <xs:element name="competencias_socio_profesionales" type="competencias_socio_profesionales1"/>
            <xs:element name="datos_adicionales" type="datos_adicionales1"/>
        </xs:sequence>
    </xs:complexType>
    <!-- LOS DATOS PERSONALES -->
    <xs:complexType name="datos_personales1">
        <xs:sequence>
            <xs:element name="nombre" type="xs:string"/>
            <xs:element name="apellidos" type="xs:string"/>
            <xs:element name="fecha_nacimiento" type="xs:date"/>
            <xs:element name="lugar_nacimiento" type="xs:string"/>
            <xs:element name="nacionalidades" type="nacionalidades1"/>
            <xs:element name="num_identificacion" type="tipo_nif"/>
            <xs:element name="foto_archivo" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <!-- LA NACIONALIDAD -->
    <xs:complexType name="nacionalidades1">
        <xs:sequence>
            <xs:element name="nacionalidad" type="xs:string" />
        </xs:sequence>
    </xs:complexType>
    <!-- DATOS DE CONTACTO -->
    <xs:complexType name="datos_contacto1">
        <xs:sequence>
            <xs:element name="tipo_via" type="xs:string"/>
            <xs:element name="nombre_via" type="xs:string"/>
            <xs:element name="numero" type="xs:integer" minOccurs="0"/>
            <xs:element name="portal" type="xs:integer" minOccurs="0"/>
            <xs:element name="escalera" type="xs:string" minOccurs="0"/>
            <xs:element name="piso" type="xs:integer" minOccurs="0"/>
            <xs:element name="puerta" type="xs:string" minOccurs="0"/>
            <xs:element name="codigo_postal" type="xs:string"/>
            <xs:element name="pais" type="xs:string"/>
            <xs:element name="email" type="xs:string"/>
            <xs:element name="telefono_movil" type="xs:string"/>
            <xs:element name="telefono_fijo" type="xs:string" minOccurs="0"/>
            <xs:element name="pagina_web" type="xs:string" minOccurs="0"/>
            <xs:element name="redes_sociales" type="redes_sociales1" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <!-- LAS REDES SOCIALES -->
    <xs:complexType name="redes_sociales1">
        <xs:sequence>
            <xs:element name="red_social" type="xs:string" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <!-- LAS FORMACIONES ACADEMICAS -->
    <xs:complexType name="formacion_academica1">
        <xs:sequence>
            <xs:element name="estudios" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="nombre" type="xs:string"/>
                        <xs:element name="lugar_realizacion" type="xs:string"/>
                        <xs:element name="fecha_inicio" type="xs:date"/>
                        <xs:element name="fecha_fin" type="xs:date"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <!-- LOS IDIOMAS -->
    <xs:complexType name="idiomas1">
        <xs:sequence>
            <xs:element name="idioma" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="nombre" type="xs:string"/>
                        <!-- NIVEL IDIOMA ALTO/MEDIO/BAJO -->
                        <xs:element name="expresion_oral" type="nivel_idioma" minOccurs="0"/>
                        <xs:element name="comprension_oral" type="xs:string" minOccurs="0"/>
                        <xs:element name="expresion_escrita" type="xs:string" minOccurs="0"/>
                        <xs:element name="comprension_escrita" type="xs:string" minOccurs="0"/>
                        <xs:element name="titulo_acreditativo" type="xs:string" minOccurs="0"/>
                        <!-- NIVEL TITULO -->
                        <xs:element name="nivel_titulo" type="nivel_titulo" minOccurs="1"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <!-- LA EXPERIENCIA LABORAL -->
    <xs:complexType name="experiencia_laboral1">
        <xs:sequence>
            <xs:element name="experiencia" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="lugar" type="xs:string"/>
                        <xs:element name="puesto" type="xs:string"/>
                        <xs:element name="fecha_inicio" type="xs:date"/>
                        <xs:element name="fecha_fin" type="xs:date"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <!-- Las competencias socio profesionales-->
    <xs:complexType name="competencias_socio_profesionales1">
        <xs:sequence>
            <xs:element name="competencia" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="nombre" type="xs:string"/>
                        <xs:element name="nivel" type="nivel_COMPETENCIA"  />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <!-- Nivel de competencia  -->
    <xs:simpleType name="nivel_COMPETENCIA">
        <xs:restriction base="xs:integer">
            <xs:enumeration value="1" />
            <xs:enumeration value="2" />
            <xs:enumeration value="3" />
            <xs:enumeration value="4" />
            <xs:enumeration value="5" />
        </xs:restriction>
    </xs:simpleType>
 <!-- TIPO DE NIF -->
    <xs:simpleType name="tipo_nif">
  <xs:restriction base="xs:string">
    <xs:pattern value="[0-9]{8}[A-Z]{1}" />
  </xs:restriction>
</xs:simpleType>

    <!-- LOS DATOS ADICIONALES -->
    <xs:complexType name="datos_adicionales1">
        <xs:sequence>
            <xs:element name="aficiones" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="aficion" type="xs:string" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="disponibilidad_viajar" type="xs:boolean" minOccurs="0"/>
            <xs:element name="vehiculo_propio" type="xs:boolean" minOccurs="0"/>
            <xs:element  name="licencias_permisosDecond" type="tipo_licencia"/>
        </xs:sequence>
    </xs:complexType>

     <!-- Tipos de licencias -->
    <xs:simpleType name="tipo_licencia">
        <xs:restriction base="xs:string">
            <xs:enumeration value="AM" />
            <xs:enumeration value="A1" />
            <xs:enumeration value="A2" />
            <xs:enumeration value="A" />
            <xs:enumeration value="B" />
            <xs:enumeration value="B+E" />
            <xs:enumeration value="C1" />
            <xs:enumeration value="C" />
            <xs:enumeration value="D1" />
            <xs:enumeration value="D1+E" />
            <xs:enumeration value="D" />
            <xs:enumeration value="BTP" />
        </xs:restriction>
    </xs:simpleType>
    <!-- LOS VALORES POSIBLES EN NIVEL DEL TITULO DE IDIOMAS -->
    <xs:simpleType name="nivel_idioma">
        <xs:restriction base="xs:string">
            <xs:enumeration value="bajo" />
            <xs:enumeration value="medio" />
            <xs:enumeration value="alto" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="nivel_titulo">
        <xs:restriction base="xs:string">
            <xs:enumeration value="A1"/>
            <xs:enumeration value="A2"/>
            <xs:enumeration value="B1"/>
            <xs:enumeration value="B2"/>
            <xs:enumeration value="C1"/>
            <xs:enumeration value="C2"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== Mirf2404/Lenguaje-de-marcas/XML/XML_TRABAJO/TRABAJO.xml
<?xml version="1.0" encoding="UTF-8"?>
<curriculum xmlns="ejer" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="ejer TRABAJOSCHEMA.xsd">
    <datos_perso>
        <nombre>holA</nombre>
        <apellidos>asdf</apellidos>
        <fecha_nacimiento>2004-04-24</fecha_nacimiento>
        <lugar_nacimiento>dsa</lugar_nacimiento>
        <nacionalidades>
            <nacionalidad>asdf</nacionalidad>
        </nacionalidades>
        <num_identificacion>asdf</num_identificacion>
        <foto_archivo>afsd</foto_archivo>
    </datos_perso>
    <datos_contacto>
        <tipo_via></tipo_via>
        <nombre_via></nombre_via>
        <numero>1</numero>
        <portal>1</portal>
        <escalera></escalera>
        <piso>1</piso>
        <puerta></puerta>
        <codigo_postal></codigo_postal>
        <pais></pais>
        <email></email>
        <telefono_movil></telefono_movil>
        <telefono_fijo></telefono_fijo>
        <pagina_web></pagina_web>
        <redes_sociales>
            <red_social></red_social>
        </redes_sociales>
    </datos_contacto>
    <formacion_academica>
        <estudios>
            <nombre></nombre>
            <lugar_realizacion></lugar_realizacion>
            <fecha_inicio>2004-04-24</fecha_inicio>
            <fecha_fin>2004-04-24</fecha_fin>
        </estudios>
    </formacion_academica>
    <idiomas>
        <idioma>
            <nombre></nombre>
            <expresion_oral>alto</expresion_oral>
            <comprension_oral></comprension_oral>
            <expresion_escrita></expresion_escrita>
            <comprension_escrita></comprension_escrita>
            <titulo_acreditativo></titulo_acreditativo>
            <nivel_titulo>A1</nivel_titulo>
        </idioma>
    </idiomas>
    <experiencia_laboral>
        <experiencia>
            <lugar></lugar>
            <puesto></puesto>
            <fecha_inicio>2004-04-24</fecha_inicio>
            <fecha_fin>2004-04-24</fecha_fin>
        </experiencia>
    </experiencia_laboral>
    <competencias_socio_profesionales>
        <competencia>
            <nombre></nombre>
            <nivel></nivel>
        </competencia>
    </competencias_socio_profesionales>
    <datos_adicionales>
        <aficiones>
            <aficion></aficion>
        </aficiones>
        <disponibilidad_viajar>true</disponibilidad_viajar>
        <vehiculo_propio>true</vehiculo_propio>
        <licencias_permisosDecond>A1</licencias_permisosDecond>
    </datos_adicionales>
</curriculum>
